name: Build and Deploy Spring Boot to AWS EC2
on:
  push:
    branches: [main]
env:
  PROJECT_NAME: Clone_What_Is
  BUCKET_NAME: whatismybucket
  CODE_DEPLOY_APP_NAME: whatiscicd
  DEPLOYMENT_GROUP_NAME: cicd_deploy
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt-openj9'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
      - name : Set YML
        run : |
          echo "${{secrets.APPLICATION_SECRET_KEY}}" | base64 --decode > src/main/resources/application-secret.yml
          find src
      - name : Set AWSYML
        run : |
          echo "${{secrets.AWS_APPLICATION_KEY}}" | base64 --decode > src/main/resources/application-aws.yml
          find src
      - name: Build with Gradle
        run: |
          ./gradlew build
          ./gradlew bootJar
        shell: bash
      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ap-northeast-2
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
